"""
Step 4: Convert community summaries into vector index for semantic search.
Input: hierarchy.pkl (generated by hierarchy_index.py)
Output:
    - community_embeddings.npy   (numpy array of shape [n_communities, embedding_dim])
    - community_metadata.json    (list of dicts with id, summary, entities, chunks)
"""

import os
import json
import pickle
import numpy as np
from typing import Dict, Any, List

# 假设你已经有这些工具函数（可以在 utils.py 中定义，或者直接从 server.settings 导入）
# 为了代码自包含，这里提供一个简洁的嵌入获取函数，你也可以直接用 openai 库
from openai import OpenAI  # 确保安装了 openai>=1.0.0

# ---------- 配置 ----------
# 如果你使用 config.yaml，请改为从配置文件读取；这里直接硬编码示例值，在实际项目中替换成你的配置加载方式
CONFIG = {
    "openai": {
        "api_key": "sk-your-api-key",  # 替换为你的 API key
        "base_url": "https://api.openai.com/v1",
        "embedding_model": "text-embedding-3-small"
    },
    "paths": {
        "output_dir": "D:\\MyProjects\\ragIM\\data\\outputs"
    }
}


# 如果你已经有 utils.load_config()，可以替换下面这行
# from utils import load_config, ensure_dir, get_embedding
# 为了不依赖外部 utils，这里直接实现所需函数
def load_config(config_path: str = "config.yaml"):
    # 如果存在 config.yaml 就读取，否则使用内置 CONFIG
    if os.path.exists(config_path):
        import yaml
        with open(config_path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)
    return CONFIG


def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


def get_embedding(text: str, model: str, client: OpenAI) -> List[float]:
    """获取文本的 embedding 向量"""
    text = text.replace("\n", " ")
    response = client.embeddings.create(input=[text], model=model)
    return response.data[0].embedding


def main():
    # 1. 加载配置和模型
    config = load_config()
    openai_config = config["openai"]
    output_dir = config["paths"]["output_dir"]
    ensure_dir(output_dir)

    # 2. 初始化 OpenAI 客户端
    client = OpenAI(
        api_key=openai_config["api_key"],
        base_url=openai_config.get("base_url", "https://api.openai.com/v1")
    )
    embedding_model = openai_config.get("embedding_model", "text-embedding-3-small")

    # 3. 加载 hierarchy.pkl
    hierarchy_path = os.path.join(output_dir, "hierarchy.pkl")
    if not os.path.exists(hierarchy_path):
        print(f"Error: {hierarchy_path} not found. Run hierarchy_index.py first.")
        return
    with open(hierarchy_path, "rb") as f:
        hierarchy = pickle.load(f)  # dict: community_id -> {id, summary, entities, chunks, ...}

    if not hierarchy:
        print("No communities found in hierarchy.pkl.")
        return

    # 4. 为每个社区摘要生成向量，并收集元数据
    community_ids = []
    embeddings_list = []
    metadata_list = []

    for comm_id, comm_data in hierarchy.items():
        summary = comm_data.get("summary", "")
        if not summary.strip():
            print(f"Warning: Community {comm_id} has empty summary, skipping.")
            continue

        print(f"Embedding community {comm_id}...")
        vec = get_embedding(summary, embedding_model, client)
        embeddings_list.append(vec)
        community_ids.append(comm_id)
        # 保留查询时可能需要的信息
        metadata_list.append({
            "id": comm_id,
            "summary": summary,
            "entities": comm_data.get("entities", []),
            "chunks": comm_data.get("chunks", []),
            "node_count": comm_data.get("node_count", 0)
        })

    if not embeddings_list:
        print("No valid community embeddings generated.")
        return

    # 5. 转换为 numpy 数组并保存
    embeddings_array = np.array(embeddings_list, dtype="float32")  # [n, dim]
    embeddings_path = os.path.join(output_dir, "community_embeddings.npy")
    np.save(embeddings_path, embeddings_array)

    # 6. 保存社区 ID 列表和元数据（JSON）
    ids_path = os.path.join(output_dir, "community_ids.json")
    with open(ids_path, "w", encoding="utf-8") as f:
        json.dump(community_ids, f, ensure_ascii=False, indent=2)

    meta_path = os.path.join(output_dir, "community_metadata.json")
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata_list, f, ensure_ascii=False, indent=2)

    print(f"Ingest done: {len(embeddings_list)} communities indexed.")
    print(f"Embeddings saved to {embeddings_path}")
    print(f"IDs saved to {ids_path}")
    print(f"Metadata saved to {meta_path}")


if __name__ == "__main__":
    main()